### ISSUE TITLE
fishfeeder not working well with 6mm pellets

### ISSUE THREAD

**Issue by dhaude** [boanjo/poseidon#2]
@boanjo 
I already started my own design based on the sewer pipes you are using as well. After finding your project I stopped my design activities and build the feeder completely on your design.
I finished it during the weekend and started first tests today.
Unfortunately I am using 6mm pellets and they cause the screw to jam and the DC-Motor is not strong enough to "crack" them.
So 2 things I've in mind now:
1. I ordered a bag 3mm pellets - hoping that those are transported smoothly
or
2. I kindly ask you to provide me with you original CAD-Design Files in order to adopt the design to the 6mm pellets - any chance?

Thank you so much for sharing your 'poseidon' project - I really like it!

**Comment by boanjo** [comment]
@dhaude Yes i'm sure the 3mm pellets will do the trick, but i will upload also the models so you can edit the screw for 6mm pellets when i get back to town in a few days. I used to have 6mm pellets too in in the past but have changed completely to 3mm as i think they are easier to get a good dose but it all depends on the amount of fish too :).

**Comment by boanjo** [comment]
@dhaude btw did you see the fishfeeder/stl_step/FishFeeder Tube straight v10.step file? I forgot i had already provided the model. Import the step file in fusion 360 and you should be good to go. If it still doesn't work i'm sure the 360 files can be shared. Let me know how it goes!

**Comment by dhaude** [comment]
@boanjo - Ah, OK, I will try that.
My strategy is the following: I will get some 3mm pellets by tomorrow and if this goes well - I'll change to those without any changes.
I also ordered a 360 degree Servo with much higher torque and will check this as well. 
Only if that will not do the job - I'll try to change the dimensions of the mechanics.
For your information: I added ElegantOTA support to your code - so debug and small SW changes can now be loaded via WiFi without going out and opening the feeder.
I also found a small Software flaw in your code - some double quotes for `clientId` were missing.
Should be:
#endif
    String payload = "{\"type\":\"periodic_wifi_mqtt\",";
    payload += "\"micros\":";
    payload += micros();
    payload += ",\"rssi\":";
    payload += rssi;
    payload += ",\"cnt_reconnect\":";
    payload += cntReconnectAttempt;
    payload += ",\"client\":\"";
    payload += clientId;
    payload += "\"}";

Thanks again for this project and have a nice day.

**Comment by dhaude** [comment]
just noticed that the backslashes were not shown:

<img width="456" alt="Bildschirmfoto 2023-08-08 um 11 26 34" src="https://github.com/boanjo/poseidon/assets/42463588/1e887ad9-beee-421a-bd6b-9e635aabfa6f">

**Comment by boanjo** [comment]
Fixed, thanks! I wasn't using the message more than observing so i had missed that for sure.

Yes, i agree it makes sense to add the OTA support and i do so also for more "changing" projects. The fishfeeder has been doing what it should for a number of years and i've strived to keep the sketches as minimal as possible.
